# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
      - releases/*
      - develop
  paths:
    exclude:
      - Backend/CMS
  batch: true

resources:
  repositories:
    - repository: self
    - repository: templates
      type: git
      name: Tools/shared-pipelines

variables:
  dockerRegistryServiceConnection: '10788c2d-887a-4d05-b118-1b4013c8301b'

stages:
- template: dotnet-pipeline.yml@templates
  parameters:
    additionalVariables:
      projectName: 'app-module-01'
      imageRepository: 'app-module-01'
      dockerfilePath: '$(Build.SourcesDirectory)/Backend/Services/Indexing.API/Dockerfile'
      tag: '$(Build.BuildId)'
      containerRegistry: 'mtrcontainerreg.azurecr.io'
